spring.application.name=Onepiece
spring.datasource.url=jdbc:mysql://localhost:3306/student_db
spring.datasource.username=root
spring.datasource.password=surya2006

logging.file.path=logs
logging.file.name=${logging.file.path}/${spring.application.name}.log
logging.logback.rollingpolicy.file-name-pattern=${logging.file.path}/${spring.application.name}-%d{yyyy-MM-dd}-%i.log
logging.logback.rollingpolicy.max-file-size=10KB

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true